





export const metadata = {
  title: " nxt js api route craete ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 <>
 <h2>hello</h2>
 {children}
 </>
  );
}




 // or `v1X-appRouter` if you are using Next.js v1X
